[mysql]
name = "company_db_1234"
addr = "127.0.0.1:6033"
port = 6033
user = "root"
pass = "root"
server_id = 1

[source_rules]
include_schemas = [
    "test_.*",
    ""
]

exclude_schemas = [
    "test_123"
]

include_tables = [
    "table_.*"
]

exclude_tables = [
    "table_1"
]

[[transform_rule]]
name = "generic"
match_schema = "test_.*"
match_table = "test_.*"
transform_func = """
function transform(cdc_event) {
    cdc_event.ext = 1
    cdc_event.after.forEach((el) => {
        el.changed = 1

        if (el.text_col.length > 3) {
            el.text_col = tObfString(el.text_col)
        }
    });
    return cdc_event
}
"""

[[transform_rule]]
name = "another-rule"
match_schema = "tenant_.*"
match_table = "entity_1"
transform_func = """
function transform(cdc_event) {
}
"""

[kafka_sink]
name = "kafka-company-db"
addr = "192.168.1.1"
port = 9222
batch_size_bytes = 2048